base_url: "http://192.168.1.100:8080"
admin_password: "admin123"
admin_route: "admin"
port: 8080
groups:
  group1:
    name: "Основные"
    urls:
      - "https://test1.com"
      - "https://test2.com"