# config.yaml
base_url: "https://test.com.net"
admin_password: "admin123"
admin_route: "admin_panel"
port: 8080

groups:
  group1:
    name: "Основные"
    urls:
      - "https://test-1.com"
      - "https://test-2.com"