# config.yaml
base_url: "https://test.com.net"
admin_password: "admin123"
admin_route: "djufbsjrlhddyg/admin"  # ← путь к админке (без слэшей)
port: 8080

groups:
  group1:
    name: "Основные"
    urls:
      - "https://46465"
      - "https://46465"